### ISSUE TITLE
Mantenimiento de empleados.

### ISSUE THREAD

**Issue by sail3** [sail3/Metrica-Andina#4]
Se desea realizar un pequeño prototipo de aplicación web que tiene como finalidad registrar y evaluar a los empleados de la empresa Developers SAC.  
- [x] #5 Listado de todos los empleados.
- [x] #6 Detalle de cada empleado.
- [x] #7 Crear un servicio XML para buscar los empleados.
## ASSETS:
- Debe tomar en cuenta el siguiente archivo en formato json para la creacion de la aplicacion:
[Empleados.json]( https://goo.gl/wmV5K1).
